<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <NoWarn>$(NoWarn);SYSLIB5001</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\FAI.Core.Extensions.DI\FAI.Core.Extensions.DI.csproj" />
        <ProjectReference Include="..\..\..\FAI.Extensions.DependencyInjection.LocalServices\FAI.Extensions.DependencyInjection.LocalServices.csproj" />
        <ProjectReference Include="..\..\..\FAI.NLP\FAI.NLP.csproj"/>
        <ProjectReference Include="..\..\..\FAI.Onnx\FAI.Onnx.csproj"/>
        <ProjectReference Include="..\..\..\FAI.Core\FAI.Core.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <AdditionalFiles Include="ClassificationModelResources\added_tokens.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </AdditionalFiles>
        <AdditionalFiles Include="ClassificationModelResources\config.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </AdditionalFiles>
        <AdditionalFiles Include="ClassificationModelResources\model.onnx">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </AdditionalFiles>
        <AdditionalFiles Include="ClassificationModelResources\special_tokens_map.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </AdditionalFiles>
        <AdditionalFiles Include="ClassificationModelResources\tokenizer.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </AdditionalFiles>
        <AdditionalFiles Include="ClassificationModelResources\tokenizer_config.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </AdditionalFiles>
        <AdditionalFiles Include="ClassificationModelResources\vocab.txt">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </AdditionalFiles>
        <AdditionalFiles Include="ClassificationModelResources\model_optimized.onnx">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </AdditionalFiles>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.9" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.9" />
      <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.9" />
      <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.9" />
      <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" Version="9.0.9" />
    </ItemGroup>

</Project>
