<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <NoWarn>$(NoWarn);SYSLIB5001</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\FAI.Core\FAI.Core.csproj"/>
        <PackageReference Include="Microsoft.ML.Tokenizers" Version="2.0.0-preview.25503.2" />
    </ItemGroup>

</Project>
