<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="MultipleChoiceModelResources\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\ML.Infra\ML.Infra.csproj" />
      <ProjectReference Include="..\..\..\ML.NLP\ML.NLP.csproj" />
      <ProjectReference Include="..\..\..\ML.Onnx\ML.Onnx.csproj" />
    </ItemGroup>

    <ItemGroup>
        <AdditionalFiles Include="MultipleChoiceModelResources\config.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </AdditionalFiles>
        <AdditionalFiles Include="MultipleChoiceModelResources\special_tokens_map.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </AdditionalFiles>
        <AdditionalFiles Include="MultipleChoiceModelResources\tokenizer.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </AdditionalFiles>
        <AdditionalFiles Include="MultipleChoiceModelResources\tokenizer_config.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </AdditionalFiles>
        <AdditionalFiles Include="MultipleChoiceModelResources\vocab.txt">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </AdditionalFiles>
        <AdditionalFiles Include="MultipleChoiceModelResources\model.onnx">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </AdditionalFiles>
        <AdditionalFiles Include="MultipleChoiceModelResources\model_optimized.onnx">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </AdditionalFiles>
    </ItemGroup>
    
</Project>
