<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <NoWarn>$(NoWarn);SYSLIB5001</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\FAI.Core\FAI.Core.csproj"/>
        <PackageReference Include="Microsoft.ML.Tokenizers" Version="2.0.0-preview.25373.1" />
    </ItemGroup>

</Project>
