<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="MultipleChoiceModelResources\" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\src\FAI.Core.Extensions.DI\FAI.Core.Extensions.DI.csproj" />
        <ProjectReference Include="..\..\..\src\FAI.Core\FAI.Core.csproj"/>
        <ProjectReference Include="..\..\..\src\FAI.Extensions.DependencyInjection.LocalServices\FAI.Extensions.DependencyInjection.LocalServices.csproj" />
        <ProjectReference Include="..\..\..\src\FAI.NLP\FAI.NLP.csproj"/>
        <ProjectReference Include="..\..\..\src\FAI.Onnx\FAI.Onnx.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <AdditionalFiles Include="MultipleChoiceModelResources\config.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </AdditionalFiles>
        <AdditionalFiles Include="MultipleChoiceModelResources\special_tokens_map.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </AdditionalFiles>
        <AdditionalFiles Include="MultipleChoiceModelResources\tokenizer.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </AdditionalFiles>
        <AdditionalFiles Include="MultipleChoiceModelResources\tokenizer_config.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </AdditionalFiles>
        <AdditionalFiles Include="MultipleChoiceModelResources\vocab.txt">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </AdditionalFiles>
        <AdditionalFiles Include="MultipleChoiceModelResources\model.onnx">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </AdditionalFiles>
        <AdditionalFiles Include="MultipleChoiceModelResources\model_optimized.onnx">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </AdditionalFiles>
    </ItemGroup>

</Project>
