<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PublishAot>true</PublishAot>
        <OptimizationPreference>true</OptimizationPreference>
        <IlcInstructionSet>avx2,bmi2,fma,pclmul,popcnt,aes</IlcInstructionSet>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Humanizer" Version="2.14.1" />
        <PackageReference Include="Microsoft.ML.OnnxRuntime.Gpu" Version="1.22.1"/>
        <PackageReference Include="Parquet.Net" Version="5.0.2"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\FAI.Core\FAI.Core.csproj"/>
        <ProjectReference Include="..\Example.SentimentInference.Model\Example.SentimentInference.Model.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Update="train-00000-of-00001.parquet">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>
