<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\FAI.Onnx\FAI.Onnx.csproj" />
  </ItemGroup>

  <ItemGroup>
      <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.29.0" />
      <PackageReference Update="NSubstitute" Version="6.2.0" />
      <PackageReference Update="xunit.v3" Version="4.0.0" />
  </ItemGroup>

</Project>
