<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <NoWarn>$(NoWarn);SYSLIB5001</NoWarn>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\ML.Infra\ML.Infra.csproj" />
      <PackageReference Include="Microsoft.ML.Tokenizers" Version="1.0.0"/>
    </ItemGroup>

</Project>
