<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Example.MultipleChoice.Model\Example.MultipleChoice.Model.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.ML.OnnxRuntime.Gpu" Version="1.21.0" />
        <PackageReference Include="Parquet.Net" Version="5.0.2"/>
    </ItemGroup>

    <ItemGroup>
        <AdditionalFiles Include="swag_train.parquet">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </AdditionalFiles>
    </ItemGroup>
</Project>
